name: Static Deploy Next.js to HostGator

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Prepare for static build (remove API routes)
        run: node scripts/prepare-static.mjs
        env:
          DEPLOY_TARGET: hostgator

      - name: Build static site
        run: npm run build:static
        env:
          DEPLOY_TARGET: hostgator

      - name: Deploy static site to HostGator
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: './out/'
          server-dir: '/'
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
            README.md

      - name: Restore API routes after build
        run: node scripts/prepare-static.mjs
        env:
          DEPLOY_TARGET: ""

      - name: Deploy Success
        run: |
          echo "✅ Deploy estático concluído com sucesso!"
          echo "🌐 Site disponível em: https://grupovettra.com.br"
          echo "📁 Arquivos HTML deployados da pasta './out/'"
