name: Deploy Next.js App to HostGator

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      # CORREÇÃO 1: Gerar o cliente Prisma ANTES do build
      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
      # CORREÇÃO 2: Build da aplicação DEPOIS da geração do cliente
      - name: Build Application
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      
      - name: Deploy to HostGator via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home3/luca9384/grupovettra.com.br/ 
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
            README.md

      - name: Run Post-Deploy Commands via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          script: |
            cd /home3/luca9384/grupovettra.com.br/
            npm install --production
            npx prisma generate
            npx prisma migrate deploy
            if [ ! -d "tmp" ]; then
              mkdir tmp
            fi
            touch tmp/restart.txt
